#!/bin/sh
#
# See https://github.com/rhysd/cargo-husky#readme
#

set -e

if ! command -v just > /dev/null; then
    echo "`just` is not installed. See https://github.com/casey/just#readme for installation instructions, or just run"
    echo ""
    echo "  cargo install just"
    echo ""
    exit 1
fi

echo "+just git-pre-push"
just git-pre-push
