#!/bin/sh
#
# PROVIDE: martin
# REQUIRE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name=martin
rcvar=${name}_enable

load_rc_config $name

pidfile="/var/run/${name}.pid"
procname="/usr/local/lib/erlang/erts-14.2.5.12/bin/beam.smp"
confdir="/usr/local/etc/martin.d"
logfile="/var/log/${name}.log"

martin_env_file="/usr/local/etc/martin.d/martin.env"

command="/usr/local/libexec/martin/entrypoint.sh"
command_args=" run"
start_precmd="${name}_prestart"
start_postcmd="${name}_poststart"
start_cmd="${name}_start"
remote_cmd="${name}_remote"
extra_commands="remote"

MARTIN_CONF_DIR="${confdir}"
: ${RELEASE_TMP:="/var/run/${name}"}
: ${ERL_CRASH_DUMP:="${RELEASE_TMP}/${name}_erl_crash.dump"}

martin_prestart()
{
  if [ ! -d "${RELEASE_TMP}" ]; then
    echo "Creating ${RELEASE_TMP}."
    mkdir $RELEASE_TMP
    chmod 740 $RELEASE_TMP

  fi
}

martin_poststart()
{
  pid="$(cat ${pidfile})"
  echo "Service ${name} started as pid ${pid}."
}

martin_start()
{
  export MARTIN_CONF_DIR RELEASE_TMP ERL_CRASH_DUMP

  rm -f ${pidfile}


  daemon -t $name -p $pidfile -f -H -o $logfile  $command $command_args

}

martin_remote()
{
  export TERM=xterm
  export PATH=/usr/local/lib/erlang28/bin:$PATH

  $command shell
}

run_rc_command "$@"
