/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/font/{fontstack}/{start}-{end}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_font"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return 200 OK if healthy. Used for readiness and liveness probes. */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sdf_sprite/{source_ids}.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_sprite_sdf_json"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sdf_sprite/{source_ids}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_sprite_sdf_png"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sprite/{source_ids}.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_sprite_json"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sprite/{source_ids}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_sprite_png"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/style/{style_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_style_json"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/style/{style_id}/static/{camera}/{size}.{format}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Render a static map image at an arbitrary camera into `{size}.{format}`. */
        get: operations["get_rendered_static_style"];
        put?: never;
        /**
         * Render a static map image with optional vector overlays.
         *     See [our documentation](https://maplibre.org/martin/sources-styles/) for
         *     the supported `sources`/`layers` subset of the maplibre style spec.
         * @description An empty or missing body renders the base map alone.
         */
        post: operations["post_rendered_static_style"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/style/{style_id}/{z}/{x}/{y}.{format}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_rendered_tile_style"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{source_ids}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_source_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{source_ids}/{z}/{x}/{y}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_tile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Catalog: {
            fonts: {
                [key: string]: {
                    /** @description Last Unicode codepoint available. */
                    end: number;
                    /** @description Font family name (e.g., "Arial"). */
                    family: string;
                    format?: null | components["schemas"]["FontFormat"];
                    /**
                     * Format: int32
                     * @description Total number of glyphs in this font.
                     */
                    glyphs: number;
                    /**
                     * Format: date-time
                     * @description Timestamp of the source font file's last modification.
                     */
                    last_modified_at?: string | null;
                    /** @description First Unicode codepoint available. */
                    start: number;
                    /**
                     * @description Font style (e.g., "Bold", "Italic").
                     *
                     *     None for regular style.
                     */
                    style?: string | null;
                };
            };
            /** @description Server-wide capability flags */
            settings: {
                /** @description Whether server-side style rendering endpoints are enabled. */
                rendering: boolean;
            };
            sprites: {
                [key: string]: {
                    /** @description Available sprite image names. */
                    images: string[];
                    /**
                     * Format: date-time
                     * @description Timestamp of the spritesheet's last modification.
                     */
                    last_modified_at?: string | null;
                    /**
                     * Format: int64
                     * @description Total size of the spritesheet in bytes.
                     */
                    size_in_bytes?: number;
                };
            };
            styles: {
                [key: string]: {
                    /** @description Distinct colors referenced by the style, for preview swatches. */
                    colors?: string[] | null;
                    /**
                     * Format: date-time
                     * @description Timestamp of the style file's last modification.
                     */
                    last_modified_at?: string | null;
                    /**
                     * Format: int32
                     * @description Number of layers declared in the style JSON.
                     */
                    layer_count?: number | null;
                    /** @description Path to the style JSON file. */
                    path: string;
                    type?: null | components["schemas"]["StyleKind"];
                    /** @description Hash identifying the current style revision. */
                    version_hash?: string | null;
                };
            };
            tiles: {
                [key: string]: {
                    /** @description Attribution text for the data source */
                    attribution?: string | null;
                    /** @description Optional content encoding (e.g., "gzip", "deflate") */
                    content_encoding?: string | null;
                    /** @description MIME type for the tile data (e.g., "application/x-protobuf", "image/png") */
                    content_type: string;
                    /** @description Description of the tile source content */
                    description?: string | null;
                    /**
                     * Format: date-time
                     * @description Timestamp of the underlying source's last modification.
                     */
                    last_modified_at?: string | null;
                    /**
                     * Format: int32
                     * @description Number of vector layers declared by this source.
                     */
                    layer_count?: number | null;
                    /** @description Human-readable name for the tile source */
                    name?: string | null;
                };
            };
        };
        /**
         * @description Source font file container format.
         * @enum {string}
         */
        FontFormat: "otf" | "ttf" | "ttc";
        StaticCirclePaint: {
            /**
             * @description CSS color for the circle.
             * @example #FF0000
             */
            "circle-color"?: string | null;
            /**
             * Format: float
             * @description Circle opacity in `0..=1`.
             */
            "circle-opacity"?: number | null;
            /**
             * Format: float
             * @description Circle radius in pixels at the rendered scale.
             * @example 6
             */
            "circle-radius"?: number | null;
            "circle-stroke-color"?: string | null;
            /** Format: float */
            "circle-stroke-opacity"?: number | null;
            /** Format: float */
            "circle-stroke-width"?: number | null;
        };
        StaticFillPaint: {
            /**
             * @description CSS color for the polygon fill.
             * @example #95BEFA
             */
            "fill-color"?: string | null;
            /**
             * Format: float
             * @description Fill opacity in `0..=1`.
             * @example 0.5
             */
            "fill-opacity"?: number | null;
            /**
             * @description CSS color for the polygon outline. Maplibre draws this only when the
             *     fill layer has no `fill-pattern`.
             */
            "fill-outline-color"?: string | null;
        };
        /** @description GeoJSON source with inline `data`. Mirrors maplibre's `geojson` source type. */
        StaticGeoJsonSource: {
            /** @description Inline GeoJSON object. URLs and strings are rejected. */
            data: unknown;
            /** @description Always `"geojson"`; other source types are rejected. */
            type: components["schemas"]["StaticGeoJsonSourceTag"];
        };
        /** @enum {string} */
        StaticGeoJsonSourceTag: "geojson";
        StaticLineLayout: {
            /** @description One of `butt`, `round`, `square`. */
            "line-cap"?: string | null;
            /** @description One of `miter`, `bevel`, `round`. */
            "line-join"?: string | null;
        };
        StaticLinePaint: {
            /**
             * @description CSS color for the line.
             * @example #285DAA
             */
            "line-color"?: string | null;
            /**
             * Format: float
             * @description Line opacity in `0..=1`.
             */
            "line-opacity"?: number | null;
            /**
             * Format: float
             * @description Line width in pixels at the rendered scale.
             * @example 3
             */
            "line-width"?: number | null;
        };
        /**
         * @description Tagged-by-`type` overlay layer. Only literal paint/layout values; no
         *     data-driven expressions, no symbol/heatmap/raster layers.
         */
        StaticOverlayLayer: {
            /** @description Base-style layer id to insert before. Optional. */
            before?: string | null;
            id: string;
            paint?: null | components["schemas"]["StaticFillPaint"];
            source: string;
            /** @enum {string} */
            type: "fill";
        } | {
            before?: string | null;
            id: string;
            layout?: null | components["schemas"]["StaticLineLayout"];
            paint?: null | components["schemas"]["StaticLinePaint"];
            source: string;
            /** @enum {string} */
            type: "line";
        } | {
            before?: string | null;
            id: string;
            paint?: null | components["schemas"]["StaticCirclePaint"];
            source: string;
            /** @enum {string} */
            type: "circle";
        };
        /**
         * @description Schema-only request body for `POST /style/.../static/...`. A partial
         *     maplibre style — `sources` (geojson only) plus `layers` (fill/line/circle
         *     only) — applied as ephemeral additions to the base style for this render.
         *
         *     Runtime parsing happens in [`OverlayBody::from_request`] via
         *     [`parse_spec`]; this struct exists only to drive `utoipa`'s schema
         *     generation.
         */
        StaticStyleOverlay: {
            /**
             * @description Layers in render order. Layer ids must not collide; server prefixes
             *     every id with `overlay:` before handing them to maplibre.
             */
            layers: components["schemas"]["StaticOverlayLayer"][];
            /** @description GeoJSON sources keyed by source id. `data` must be inline (no URLs). */
            sources: {
                [key: string]: components["schemas"]["StaticGeoJsonSource"];
            };
        };
        /**
         * @description What kind of layers a `MapLibre` style draws.
         * @enum {string}
         */
        StyleKind: "vector" | "raster" | "hybrid";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type Catalog = components['schemas']['Catalog'];
export type FontFormat = components['schemas']['FontFormat'];
export type StaticCirclePaint = components['schemas']['StaticCirclePaint'];
export type StaticFillPaint = components['schemas']['StaticFillPaint'];
export type StaticGeoJsonSource = components['schemas']['StaticGeoJsonSource'];
export type StaticGeoJsonSourceTag = components['schemas']['StaticGeoJsonSourceTag'];
export type StaticLineLayout = components['schemas']['StaticLineLayout'];
export type StaticLinePaint = components['schemas']['StaticLinePaint'];
export type StaticOverlayLayer = components['schemas']['StaticOverlayLayer'];
export type StaticStyleOverlay = components['schemas']['StaticStyleOverlay'];
export type StyleKind = components['schemas']['StyleKind'];
export type $defs = Record<string, never>;
export interface operations {
    get_catalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalog of all configured sources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
        };
    };
    get_font: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fontstack: string;
                start: number;
                end: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Glyph PBF range */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-protobuf": unknown;
                };
            };
            /** @description Invalid glyph range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No matching font */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    get_sprite_sdf_json: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_ids: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SDF sprite index JSON */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description No matching sprite source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_sprite_sdf_png: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_ids: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Combined signed-distance-field sprite image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description No matching sprite source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_sprite_json: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_ids: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sprite index JSON */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description No matching sprite source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_sprite_png: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_ids: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Combined sprite image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description No matching sprite source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_style_json: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                style_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description MapLibre Style Spec JSON document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Style file is malformed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No matching style */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_rendered_static_style: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                style_id: string;
                /** @description `lon,lat,zoom[@bearing[,pitch]]` or `minLon,minLat,maxLon,maxLat`. */
                camera: string;
                /** @description `WIDTHxHEIGHT[@SCALEx]` - e.g. `800x600` or `400x300@2x`. */
                size: string;
                /**
                 * @description Output encoding. `png`, `jpg`, or `webp` (canonical names only;
                 *     `.jpeg` is redirected to `.jpg` via [`redirect_static_jpeg`]).
                 */
                format: "png" | "jpg" | "webp";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rendered static map image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                    "image/png": unknown;
                    "image/webp": unknown;
                };
            };
            /** @description Invalid params or size */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rendering is disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No matching style */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Renderer or encoder failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_rendered_static_style: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                style_id: string;
                /** @description `lon,lat,zoom[@bearing[,pitch]]` or `minLon,minLat,maxLon,maxLat`. */
                camera: string;
                /** @description `WIDTHxHEIGHT[@SCALEx]` - e.g. `800x600` or `400x300@2x`. */
                size: string;
                /**
                 * @description Output encoding. `png`, `jpg`, or `webp` (canonical names only;
                 *     `.jpeg` is redirected to `.jpg` via [`redirect_static_jpeg`]).
                 */
                format: "png" | "jpg" | "webp";
            };
            cookie?: never;
        };
        /** @description Partial maplibre style: `sources` (geojson only) plus `layers` (fill/line/circle only), applied for this render. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaticStyleOverlay"];
            };
        };
        responses: {
            /** @description Rendered static map image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                    "image/png": unknown;
                    "image/webp": unknown;
                };
            };
            /** @description Invalid params, size, or overlay body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rendering is disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No matching style */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Renderer or encoder failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_rendered_tile_style: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                style_id: string;
                z: number;
                x: number;
                y: number;
                format: "png" | "jpg" | "webp";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-side rendered style tile (PNG/JPEG/WebP) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid tile coordinates */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rendering is disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No matching style */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Renderer or encoder failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_source_info: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_ids: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TileJSON 3.0.0 metadata for the requested source(s) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description No matching source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_tile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_ids: string;
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Encoded vector or raster tile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Source(s) returned an empty tile */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ETag matched If-None-Match */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No matching source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No supported tile format in Accept header */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
