/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/font/{fontstack}/{start}-{end}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_font"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return 200 OK if healthy. Used for readiness and liveness probes. */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sdf_sprite/{source_ids}.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_sprite_sdf_json"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sdf_sprite/{source_ids}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_sprite_sdf_png"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sprite/{source_ids}.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_sprite_json"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sprite/{source_ids}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_sprite_png"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/style/{style_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_style_json"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{source_ids}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_source_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{source_ids}/{z}/{x}/{y}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_tile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Catalog: {
            fonts: {
                [key: string]: {
                    /** @description Last Unicode codepoint available. */
                    end: number;
                    /** @description Font family name (e.g., "Arial"). */
                    family: string;
                    /**
                     * Format: int32
                     * @description Total number of glyphs in this font.
                     */
                    glyphs: number;
                    /** @description First Unicode codepoint available. */
                    start: number;
                    /**
                     * @description Font style (e.g., "Bold", "Italic").
                     *
                     *     None for regular style.
                     */
                    style?: string | null;
                };
            };
            sprites: {
                [key: string]: {
                    /** @description Available sprite image names. */
                    images: string[];
                };
            };
            styles: {
                [key: string]: {
                    /** @description Path to the style JSON file. */
                    path: string;
                };
            };
            tiles: {
                [key: string]: {
                    /** @description Attribution text for the data source */
                    attribution?: string | null;
                    /** @description Optional content encoding (e.g., "gzip", "deflate") */
                    content_encoding?: string | null;
                    /** @description MIME type for the tile data (e.g., "application/x-protobuf", "image/png") */
                    content_type: string;
                    /** @description Description of the tile source content */
                    description?: string | null;
                    /** @description Human-readable name for the tile source */
                    name?: string | null;
                };
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaCatalog = components['schemas']['Catalog'];
export type $defs = Record<string, never>;
export interface operations {
    get_catalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalog of all configured sources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
        };
    };
    get_font: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fontstack: string;
                start: number;
                end: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Glyph PBF range */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-protobuf": unknown;
                };
            };
            /** @description Invalid glyph range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No matching font */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    get_sprite_sdf_json: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_ids: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SDF sprite index JSON */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description No matching sprite source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_sprite_sdf_png: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_ids: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Combined signed-distance-field sprite image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description No matching sprite source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_sprite_json: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_ids: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sprite index JSON */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description No matching sprite source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_sprite_png: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_ids: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Combined sprite image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description No matching sprite source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_style_json: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                style_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description MapLibre Style Spec JSON document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Style file is malformed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No matching style */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_source_info: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_ids: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TileJSON 3.0.0 metadata for the requested source(s) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description No matching source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_tile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_ids: string;
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Encoded vector or raster tile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Source(s) returned an empty tile */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ETag matched If-None-Match */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No matching source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No supported tile format in Accept header */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
