import { aggregateEndpointGroups, ENDPOINT_GROUPS, parsePrometheusMetrics } from "./prometheus";
import type { AnalyticsData, CatalogSchema } from "./types";

/**
 * Returns mock analytics data for Martin dashboard.
 * Simulates a 10% failure rate and logs when the mock is used.
 */
export function getMartinMockAnalytics(): AnalyticsData {
  // 10% chance to fail
  if (Math.random() < 0.1) {
    console.log("[MOCK] getMartinMockAnalytics: Simulated failure");
    throw new Error("Simulated mock analytics failure");
  }
  console.log("[MOCK] getMartinMockAnalytics: Returning mock analytics data");
  return {
    fonts: { averageRequestDurationMs: 2, requestCount: 17 },
    sprites: { averageRequestDurationMs: 42, requestCount: 5 },
    styles: { averageRequestDurationMs: 1, requestCount: 13 },
    tiles: { averageRequestDurationMs: 32, requestCount: 99 },
  };
}

/**
 * Returns mock catalog data for Martin dashboard.
 * Simulates a 10% failure rate and logs when the mock is used.
 */
export function getMartinMockCatalog(): CatalogSchema {
  // 10% chance to fail
  if (Math.random() < 0.1) {
    console.log("[MOCK] getMartinMockCatalog: Simulated failure");
    throw new Error("Simulated mock catalog failure");
  }
  console.log("[MOCK] getMartinMockCatalog: Returning mock catalog data");
  return {
    fonts: {
      "Roboto Black": { end: 65533, family: "Roboto", glyphs: 2767, start: 0, style: "Black" },
      "Roboto Black Italic": {
        end: 65533,
        family: "Roboto",
        glyphs: 2767,
        start: 0,
        style: "Black Italic",
      },
      "Roboto Bold": { end: 65533, family: "Roboto", glyphs: 2767, start: 0, style: "Bold" },
      "Roboto Bold Italic": {
        end: 65533,
        family: "Roboto",
        glyphs: 2767,
        start: 0,
        style: "Bold Italic",
      },
      "Roboto Condensed Bold": {
        end: 65533,
        family: "Roboto Condensed",
        glyphs: 2767,
        start: 0,
        style: "Bold",
      },
      "Roboto Condensed Bold Italic": {
        end: 65533,
        family: "Roboto Condensed",
        glyphs: 2767,
        start: 0,
        style: "Bold Italic",
      },
      "Roboto Condensed Italic": {
        end: 65533,
        family: "Roboto Condensed",
        glyphs: 2767,
        start: 0,
        style: "Italic",
      },
      "Roboto Condensed Light": {
        end: 65533,
        family: "Roboto Condensed",
        glyphs: 2767,
        start: 0,
        style: "Light",
      },
      "Roboto Condensed Light Italic": {
        end: 65533,
        family: "Roboto Condensed",
        glyphs: 2767,
        start: 0,
        style: "Light Italic",
      },
      "Roboto Condensed Medium": {
        end: 65533,
        family: "Roboto Condensed",
        glyphs: 2767,
        start: 0,
        style: "Medium",
      },
      "Roboto Condensed Medium Italic": {
        end: 65533,
        family: "Roboto Condensed",
        glyphs: 2767,
        start: 0,
        style: "Medium Italic",
      },
      "Roboto Condensed Regular": {
        end: 65533,
        family: "Roboto Condensed",
        glyphs: 2767,
        start: 0,
        style: "Regular",
      },
      "Roboto Italic": { end: 65533, family: "Roboto", glyphs: 2767, start: 0, style: "Italic" },
      "Roboto Light": { end: 65533, family: "Roboto", glyphs: 2767, start: 0, style: "Light" },
      "Roboto Light Italic": {
        end: 65533,
        family: "Roboto",
        glyphs: 2767,
        start: 0,
        style: "Light Italic",
      },
      "Roboto Medium": { end: 65533, family: "Roboto", glyphs: 2767, start: 0, style: "Medium" },
      "Roboto Medium Italic": {
        end: 65533,
        family: "Roboto",
        glyphs: 2767,
        start: 0,
        style: "Medium Italic",
      },
      "Roboto Regular": { end: 65533, family: "Roboto", glyphs: 2767, start: 0, style: "Regular" },
      "Roboto Thin": { end: 65533, family: "Roboto", glyphs: 2767, start: 0, style: "Thin" },
      "Roboto Thin Italic": {
        end: 65533,
        family: "Roboto",
        glyphs: 2767,
        start: 0,
        style: "Thin Italic",
      },
    },
    sprites: {
      maki: {
        images: [
          "aerialway",
          "airfield",
          "airport",
          "alcohol-shop",
          "american-football",
          "amusement-park",
          "animal-shelter",
          "aquarium",
          "arrow",
          "art-gallery",
          "attraction",
          "bakery",
          "bank",
          "bank-JP",
          "bar",
          "barrier",
          "baseball",
          "basketball",
          "bbq",
          "beach",
          "beer",
          "bicycle",
          "bicycle-share",
          "blood-bank",
          "bowling-alley",
          "bridge",
          "building",
          "building-alt1",
          "bus",
          "cafe",
          "campsite",
          "car",
          "car-rental",
          "car-repair",
          "casino",
          "castle",
          "castle-JP",
          "caution",
          "cemetery",
          "cemetery-JP",
          "charging-station",
          "cinema",
          "circle",
          "circle-stroked",
          "city",
          "clothing-store",
          "college",
          "college-JP",
          "commercial",
          "communications-tower",
          "confectionery",
          "construction",
          "convenience",
          "cricket",
          "cross",
          "dam",
          "danger",
          "defibrillator",
          "dentist",
          "diamond",
          "doctor",
          "dog-park",
          "drinking-water",
          "elevator",
          "embassy",
          "emergency-phone",
          "entrance",
          "entrance-alt1",
          "farm",
          "fast-food",
          "fence",
          "ferry",
          "ferry-JP",
          "fire-station",
          "fire-station-JP",
          "fitness-centre",
          "florist",
          "fuel",
          "furniture",
          "gaming",
          "garden",
          "garden-centre",
          "gate",
          "gift",
          "globe",
          "golf",
          "grocery",
          "hairdresser",
          "harbor",
          "hardware",
          "heart",
          "heliport",
          "highway-rest-area",
          "historic",
          "home",
          "horse-riding",
          "hospital",
          "hospital-JP",
          "hot-spring",
          "ice-cream",
          "industry",
          "information",
          "jewelry-store",
          "karaoke",
          "landmark",
          "landmark-JP",
          "landuse",
          "laundry",
          "library",
          "lift-gate",
          "lighthouse",
          "lighthouse-JP",
          "lodging",
          "logging",
          "marae",
          "marker",
          "marker-stroked",
          "mobile-phone",
          "monument",
          "monument-JP",
          "mountain",
          "museum",
          "music",
          "natural",
          "nightclub",
          "observation-tower",
          "optician",
          "paint",
          "park",
          "park-alt1",
          "parking",
          "parking-garage",
          "parking-paid",
          "pharmacy",
          "picnic-site",
          "pitch",
          "place-of-worship",
          "playground",
          "police",
          "police-JP",
          "post",
          "post-JP",
          "prison",
          "racetrack",
          "racetrack-boat",
          "racetrack-cycling",
          "racetrack-horse",
          "rail",
          "rail-light",
          "rail-metro",
          "ranger-station",
          "recycling",
          "religious-buddhist",
          "religious-christian",
          "religious-jewish",
          "religious-muslim",
          "religious-shinto",
          "residential-community",
          "restaurant",
          "restaurant-bbq",
          "restaurant-noodle",
          "restaurant-pizza",
          "restaurant-seafood",
          "restaurant-sushi",
          "road-accident",
          "roadblock",
          "rocket",
          "school",
          "school-JP",
          "scooter",
          "shelter",
          "shoe",
          "shop",
          "skateboard",
          "skiing",
          "slaughterhouse",
          "slipway",
          "snowmobile",
          "soccer",
          "square",
          "square-stroked",
          "stadium",
          "star",
          "star-stroked",
          "suitcase",
          "swimming",
          "table-tennis",
          "taxi",
          "teahouse",
          "telephone",
          "tennis",
          "terminal",
          "theatre",
          "toilet",
          "toll",
          "town",
          "town-hall",
          "triangle",
          "triangle-stroked",
          "tunnel",
          "veterinary",
          "viewpoint",
          "village",
          "volcano",
          "volleyball",
          "warehouse",
          "waste-basket",
          "watch",
          "water",
          "waterfall",
          "watermill",
          "wetland",
          "wheelchair",
          "windmill",
          "zoo",
        ],
      },
      navigatum: {
        images: [
          "bus-munich",
          "default_1",
          "default_2",
          "default_3",
          "default_4",
          "default_5",
          "default_6",
          "exit-alt1",
          "noun-shower-51",
          "rounded_rectangle",
          "rounded_rombos",
          "s-bahn-munich",
          "temaki-bench",
          "temaki-tree-and-bench",
          "toilet_female",
          "toilet_male",
          "tram-munich",
          "turnstile",
          "u-bahn-munich",
        ],
      },
    },
    styles: { "navigatum-basemap": { path: "map/navigatum-basemap.json" } },
    tiles: {
      indoor_nodes: {
        content_type: "application/x-protobuf",
        description: "public.indoor_nodes.geom",
      },
      indoor_polygons: {
        content_type: "application/x-protobuf",
        description: "public.indoor_polygons.geom",
      },
      indoor_ways: {
        content_type: "application/x-protobuf",
        description: "public.indoor_ways.geom",
      },
      shortbread: {
        attribution:
          '<a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>',
        content_encoding: "gzip",
        content_type: "application/x-protobuf",
        description:
          "A basic, lean, general-purpose vector tile schema for OpenStreetMap data. See https://shortbread.geofabrik.de/",
        name: "Shortbread",
      },
    },
  };
}
