#!/usr/bin/env just --justfile

set shell := ["bash", "-c"]

dockercompose := `if docker-compose --version &> /dev/null; then echo "docker-compose"; else echo "docker compose"; fi`

@_default:
    just --list --unsorted

clean:
    rm -rf frontend/node_modules

up:
   {{ dockercompose }} up

up-build:
    {{ dockercompose }} up --build

build:
    {{ dockercompose }} build

up-backend:
    {{ dockercompose }} up db tiles --detach

frontend *ARGS:
    {{ dockercompose }} up frontend {{ ARGS }}

[no-exit-message]
frontend-sh:
    {{ dockercompose }} run --interactive --entrypoint sh frontend
