name: Benchmark

on:
  #  push:
  #    branches: [ main ]
  #    paths-ignore:
  #      - '**.md'
  #      - 'demo/**'
  #      - 'docs/**'
  #  pull_request:
  #    types: [ opened, synchronize, reopened ]
  #    paths-ignore:
  #      - '**.md'
  #      - 'demo/**'
  #      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check_benchmark:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout sources
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with: { persist-credentials: false }

      - name: Check benchmark
        run: cargo bench
