name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { persist-credentials: false }

      - name: 'Validate .md files (use "just fmt-md" to fix)'
        uses: DavidAnson/markdownlint-cli2-action@21c1be1b93ad9ed58fa840aacc3f279cde2a72ff # v24.2.0
        with:
          config: '.github/files/config.markdownlint-cli2.jsonc'

      - name: 'Check Markdown URLs (same as "just clippy-md")'
        uses: tcort/github-action-markdown-link-check@e047c5b37f24ab722bbef1a27b6fab7f96bc4068 # v1.1.3
        with:
          use-quiet-mode: 'yes' # only of the checks that failed
          use-verbose-mode: 'yes' # show status codes
          folder-path: 'docs/content'
          file-path: './README.md'
          config-file: '.github/files/markdown.links.config.json'

      - uses: ./.github/actions/setup-rust
        with: { toolchain: none, tools: 'just,cargo-binstall' }

      - run: just -v docs-build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/book
