name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with: { persist-credentials: false }

      - name: 'Validate .md files (use "just fmt-md" to fix)'
        uses: DavidAnson/markdownlint-cli2-action@8de2aa07cae85fd17c0b35642db70cf5495f1d25 # v24.0.0
        with:
          config: '.github/files/config.markdownlint-cli2.jsonc'

      - name: 'Check Markdown URLs (same as "just clippy-md")'
        uses: tcort/github-action-markdown-link-check@e7c7a18363c842693fadde5d41a3bd3573a7a225 # v1.1.2
        with:
          use-quiet-mode: 'yes' # only of the checks that failed
          use-verbose-mode: 'yes' # show status codes
          folder-path: 'docs/content'
          file-path: './README.md'
          config-file: '.github/files/markdown.links.config.json'

      - uses: taiki-e/install-action@9bcaee1dcae34154180f412e2fa69355a7cda9f6 # v2.82.6
        with: { tool: 'just,cargo-binstall' }

      - run: just -v docs-build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/book
