name: Demo CI

on:
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  build-demo:
    name: Build the demo images
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { persist-credentials: false }
      - uses: $/.github/actions/setup-rust
        with: { toolchain: none }
      - run: just demo::build
