name: Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'demo/**'
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  demo:
    name: Demo
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout sources
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with: { persist-credentials: false }
      - uses: taiki-e/install-action@9bcaee1dcae34154180f412e2fa69355a7cda9f6 # v2.82.6
        with: { tool: just }
      - run: just demo::build
